# Generated by Django 5.2.5 on 2025-09-21 14:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Composer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('status', models.IntegerField(choices=[(1, 'Действует'), (2, 'Удалена')], default=1, verbose_name='Статус')),
                ('image', models.ImageField(blank=True, default='default.png', null=True, upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(verbose_name='Биография')),
                ('price', models.IntegerField(verbose_name='Тариф')),
                ('analyzed_works', models.IntegerField(default=0, verbose_name='Проанализировано произведений')),
                ('total_intervals', models.IntegerField(default=0, verbose_name='Всего интервалов')),
                ('period', models.CharField(blank=True, max_length=100, verbose_name='Период творчества')),
                ('polyphony_type', models.CharField(blank=True, max_length=100, verbose_name='Тип полифонии')),
                ('interval_stats', models.JSONField(default=list, help_text='Список словарей: [{"IntervalGroup": "...", "Frequency": число, "StdDev": число}, ...]', verbose_name='Статистика интервалов')),
            ],
            options={
                'verbose_name': 'Композитор',
                'verbose_name_plural': 'Композиторы',
                'db_table': 'composers',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Введён'), (2, 'В работе'), (3, 'Завершен'), (4, 'Отклонен'), (5, 'Удален')], default=1, verbose_name='Статус')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('date_formation', models.DateTimeField(blank=True, null=True, verbose_name='Дата формирования')),
                ('date_complete', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('moderator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='moderator', to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='owner', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Анализ',
                'verbose_name_plural': 'Анализы',
                'db_table': 'analysiss',
                'ordering': ('-date_formation',),
            },
        ),
        migrations.CreateModel(
            name='ComposerAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField(default=0, verbose_name='Длина')),
                ('value', models.IntegerField(blank=True, default=0, verbose_name='Значение')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='compositors.analysis', verbose_name='Анализ')),
                ('composer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='compositors.composer', verbose_name='Композитор')),
            ],
            options={
                'verbose_name': 'м-м',
                'verbose_name_plural': 'м-м',
                'db_table': 'composer_analysis',
                'ordering': ('id',),
                'unique_together': {('composer', 'analysis')},
            },
        ),
    ]
