# Generated by Django 5.2.5 on 2025-10-06 18:36

import compositors.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Composer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('status', models.IntegerField(choices=[(1, 'Действует'), (2, 'Удалена')], default=1, verbose_name='Статус')),
                ('portrait_url', models.URLField(blank=True, null=True, verbose_name='URL портрета')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='Биография')),
                ('analyzed_works', models.IntegerField(default=0, verbose_name='Проанализировано произведений')),
                ('total_intervals', models.IntegerField(default=0, verbose_name='Всего интервалов')),
                ('period', models.CharField(blank=True, max_length=100, verbose_name='Период творчества')),
                ('polyphony_type', models.CharField(blank=True, max_length=100, verbose_name='Тип полифонии')),
                ('unisons_seconds_freq', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Частота: Унисоны и секунды (%)')),
                ('unisons_seconds_stddev', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='СКО: Унисоны и секунды')),
                ('thirds_freq', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Частота: Терции (%)')),
                ('thirds_stddev', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='СКО: Терции')),
                ('fourths_fifths_freq', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Частота: Кварты и квинты (%)')),
                ('fourths_fifths_stddev', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='СКО: Кварты и квинты')),
                ('sixths_sevenths_freq', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Частота: Сексты и септимы (%)')),
                ('sixths_sevenths_stddev', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='СКО: Сексты и септимы')),
                ('octaves_freq', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Частота: Октавы (%)')),
                ('octaves_stddev', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='СКО: Октавы')),
            ],
            options={
                'verbose_name': 'Композитор',
                'verbose_name_plural': 'Композиторы',
                'db_table': 'composers',
                'ordering': ('pk',),
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', compositors.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Введён'), (2, 'В работе'), (3, 'Завершен'), (4, 'Отклонен'), (5, 'Удален')], default=1, verbose_name='Статус')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('date_formation', models.DateTimeField(blank=True, null=True, verbose_name='Дата формирования')),
                ('date_complete', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('composers_list', models.JSONField(default=list, verbose_name='Список композиторов')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_analyses', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Анализ',
                'verbose_name_plural': 'Анализы',
                'db_table': 'analysiss',
                'ordering': ('-date_formation',),
            },
        ),
        migrations.CreateModel(
            name='ComposerAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anon_unisons_seconds_freq', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Аноним: Унисоны и секунды (%)')),
                ('anon_unisons_seconds_stddev', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Аноним СКО: Унисоны и секунды')),
                ('anon_thirds_freq', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Аноним: Терции (%)')),
                ('anon_thirds_stddev', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Аноним СКО: Терции')),
                ('anon_fourths_fifths_freq', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Аноним: Кварты и квинты (%)')),
                ('anon_fourths_fifths_stddev', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Аноним СКО: Кварты и квинты')),
                ('anon_sixths_sevenths_freq', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Аноним: Сексты и септимы (%)')),
                ('anon_sixths_sevenths_stddev', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Аноним СКО: Сексты и септимы')),
                ('anon_octaves_freq', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Аноним: Октавы (%)')),
                ('anon_octaves_stddev', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Аноним СКО: Октавы')),
                ('potential_coincidence', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Вероятное совпадение')),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='compositors.analysis', verbose_name='Анализ')),
                ('composer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='compositors.composer', verbose_name='Композитор')),
            ],
            options={
                'verbose_name': 'м-м',
                'verbose_name_plural': 'м-м',
                'db_table': 'composer_analysis',
                'ordering': ('id',),
                'unique_together': {('composer', 'analysis')},
            },
        ),
    ]
