# Generated by Django 5.2.5 on 2025-09-28 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compositors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composer',
            name='image',
            field=models.URLField(blank=True, null=True, verbose_name='Изображение'),
        ),
    ]
