# Generated by Django 5.2.6 on 2025-09-17 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntervalAttribution_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composer',
            name='fourths_fifths_frequency',
        ),
        migrations.RemoveField(
            model_name='composer',
            name='fourths_fifths_std_dev',
        ),
        migrations.RemoveField(
            model_name='composer',
            name='octaves_frequency',
        ),
        migrations.RemoveField(
            model_name='composer',
            name='octaves_std_dev',
        ),
        migrations.RemoveField(
            model_name='composer',
            name='portrait_url',
        ),
        migrations.RemoveField(
            model_name='composer',
            name='seconds_frequency',
        ),
        migrations.RemoveField(
            model_name='composer',
            name='seconds_std_dev',
        ),
        migrations.RemoveField(
            model_name='composer',
            name='sixths_sevenths_frequency',
        ),
        migrations.RemoveField(
            model_name='composer',
            name='sixths_sevenths_std_dev',
        ),
        migrations.RemoveField(
            model_name='composer',
            name='thirds_frequency',
        ),
        migrations.RemoveField(
            model_name='composer',
            name='thirds_std_dev',
        ),
        migrations.AddField(
            model_name='composer',
            name='interval_stats',
            field=models.JSONField(default=list, help_text='Список словарей: [{"IntervalGroup": "...", "Frequency": число, "StdDev": число}, ...]', verbose_name='Статистика интервалов'),
        ),
    ]
