# Generated by Django 5.2.6 on 2025-09-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntervalAttribution_app', '0002_remove_composer_fourths_fifths_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composer',
            name='description',
            field=models.TextField(verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='composer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
    ]
