# Generated by Django 5.2.6 on 2025-09-17 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntervalAttribution_app', '0003_alter_composer_description_alter_composer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composeranalysis',
            name='value',
            field=models.IntegerField(blank=True, default=0, verbose_name='Значение'),
        ),
    ]
