# Generated by Django 5.2.6 on 2025-10-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntervalAttribution_app', '0004_alter_composeranalysis_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='composer',
            name='image',
        ),
        migrations.RemoveField(
            model_name='composer',
            name='price',
        ),
        migrations.AddField(
            model_name='composer',
            name='biography',
            field=models.TextField(blank=True, null=True, verbose_name='Биография'),
        ),
        migrations.AddField(
            model_name='composer',
            name='portrait_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL портрета'),
        ),
    ]
