# Generated by Django 5.2.6 on 2025-10-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntervalAttribution_app', '0005_remove_composer_description_remove_composer_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composeranalysis',
            name='length',
        ),
        migrations.RemoveField(
            model_name='composeranalysis',
            name='value',
        ),
        migrations.AddField(
            model_name='composeranalysis',
            name='anonymous_interval_stats',
            field=models.JSONField(default=list, help_text='Список словарей: [{"IntervalGroup": "...", "Frequency": число, "StdDev": число}, ...]', verbose_name='Статистика интервалов'),
        ),
        migrations.AddField(
            model_name='composeranalysis',
            name='potential_coincidence',
            field=models.IntegerField(blank=True, default=0, verbose_name='Вероятное совпадения'),
        ),
    ]
