# Generated by Django 5.2.6 on 2025-10-01 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntervalAttribution_app', '0006_remove_composeranalysis_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='composers_list',
            field=models.JSONField(default=list, verbose_name='Список композиторов'),
        ),
        migrations.AlterField(
            model_name='composeranalysis',
            name='potential_coincidence',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Вероятное совпадение'),
        ),
    ]
