# Generated by Django 5.2.7 on 2025-10-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IntervalAttribution_app', '0007_analysis_composers_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composer',
            name='interval_stats',
        ),
        migrations.RemoveField(
            model_name='composeranalysis',
            name='anonymous_interval_stats',
        ),
        migrations.AddField(
            model_name='composer',
            name='fourths_fifths_freq',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Частота: Кварты и квинты (%)'),
        ),
        migrations.AddField(
            model_name='composer',
            name='fourths_fifths_stddev',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='СКО: Кварты и квинты'),
        ),
        migrations.AddField(
            model_name='composer',
            name='octaves_freq',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Частота: Октавы (%)'),
        ),
        migrations.AddField(
            model_name='composer',
            name='octaves_stddev',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='СКО: Октавы'),
        ),
        migrations.AddField(
            model_name='composer',
            name='sixths_sevenths_freq',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Частота: Сексты и септимы (%)'),
        ),
        migrations.AddField(
            model_name='composer',
            name='sixths_sevenths_stddev',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='СКО: Сексты и септимы'),
        ),
        migrations.AddField(
            model_name='composer',
            name='thirds_freq',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Частота: Терции (%)'),
        ),
        migrations.AddField(
            model_name='composer',
            name='thirds_stddev',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='СКО: Терции'),
        ),
        migrations.AddField(
            model_name='composer',
            name='unisons_seconds_freq',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Частота: Унисоны и секунды (%)'),
        ),
        migrations.AddField(
            model_name='composer',
            name='unisons_seconds_stddev',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='СКО: Унисоны и секунды'),
        ),
        migrations.AddField(
            model_name='composeranalysis',
            name='anon_fourths_fifths_freq',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Аноним: Кварты и квинты (%)'),
        ),
        migrations.AddField(
            model_name='composeranalysis',
            name='anon_fourths_fifths_stddev',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Аноним СКО: Кварты и квинты'),
        ),
        migrations.AddField(
            model_name='composeranalysis',
            name='anon_octaves_freq',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Аноним: Октавы (%)'),
        ),
        migrations.AddField(
            model_name='composeranalysis',
            name='anon_octaves_stddev',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Аноним СКО: Октавы'),
        ),
        migrations.AddField(
            model_name='composeranalysis',
            name='anon_sixths_sevenths_freq',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Аноним: Сексты и септимы (%)'),
        ),
        migrations.AddField(
            model_name='composeranalysis',
            name='anon_sixths_sevenths_stddev',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Аноним СКО: Сексты и септимы'),
        ),
        migrations.AddField(
            model_name='composeranalysis',
            name='anon_thirds_freq',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Аноним: Терции (%)'),
        ),
        migrations.AddField(
            model_name='composeranalysis',
            name='anon_thirds_stddev',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Аноним СКО: Терции'),
        ),
        migrations.AddField(
            model_name='composeranalysis',
            name='anon_unisons_seconds_freq',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Аноним: Унисоны и секунды (%)'),
        ),
        migrations.AddField(
            model_name='composeranalysis',
            name='anon_unisons_seconds_stddev',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Аноним СКО: Унисоны и секунды'),
        ),
    ]
